### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by brandon-dacrib** [presslabs/z3#26]
when running: 
`root@cobalt:~# z3 backup`
I receive an error: 
Traceback (most recent call last):
  File "/usr/local/bin/z3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/z3/snap.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/z3/snap.py", line 607, in main
    dry=args.dry, compressor=compressor, parseable=args.parseable)
  File "/usr/local/lib/python2.7/dist-packages/z3/snap.py", line 504, in do_backup
    uploaded = pair_manager.backup_incremental(snap_name=snap_name, dry_run=dry)
  File "/usr/local/lib/python2.7/dist-packages/z3/snap.py", line 387, in backup_incremental
    z_snap.parent.name, z_snap.name),
AttributeError: 'NoneType' object has no attribute 'name'

below is my config: 
[main]
FILESYSTEM=zpool0/config
BUCKET=cobalt-backups
S3_KEY_ID=##########
S3_SECRET=######################
COMPRESSOR=pigz4
HOST=s3.wasabisys.com
CONCURRENCY=64
MAX_RETRIES=3
S3_PREFIX=z3-backup/
SNAPSHOT_PREFIX=zfs-auto-snap_hourly

I verified that the aws s3 tooling works and `root@cobalt:~# z3 status`

> backup status for zpool0/config@zfs-auto-snap_hourly* on cobalt-backups/z3-backup/
> NAME                                 | PARENT | TYPE    | HEALTH | LOCAL STATE | SIZE
> zfs-auto-snap_hourly-2018-06-21-1617 | -      | missing | -      | ok          |
> zfs-auto-snap_hourly-2018-06-21-1717 | -      | missing | -      | ok          |
> zfs-auto-snap_hourly-2018-06-21-1817 | -      | missing | -      | ok          |

seems to work. Any help troubleshooting would be appreciated.

**Comment by brandon-dacrib** [comment]
I am using wasabi, I confirmed this works with plain s3 so they must be missing something you need. Can you help me narrow it down?

**Comment by bogdanpetrea** [comment]
Hi @brandon-dacrib,

When you run `z3 backup`, by default it will try to create an **incremental** backup, so make sure you create a **full** backup first. You can run `zfs backup --help` for more info.

I'm not very familiar with the tool, but I think it can be made so that the first backup will always be a full one.

**Comment by brandon-dacrib** [comment]
That was my problem. Thank you. 
`z3  --filesystem zpool0/config backup --full`

worked.
